name = "Skyblocker Modpack"
author = "Wohlhabend/LifeIsAParadox"
version = "3.5.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "317be1afb1d717d079d3a3db99733d01628ade54a1096cfd2e1bf2007ddfe202"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
