name = "Skyblocker Modpack"
author = "Wohlhabend/LifeIsAParadox"
version = "3.5.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4050268b5fa453fcd773e14f8335bce76f2365d3619e8b18d8772e7712970188"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
