name = "Skyblocker Modpack"
author = "Wohlhabend/LifeIsAParadox"
version = "3.5.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "708723e3591ce5a7d3a97bf6134b017cfd5617e360c025fd3e63ae2c9eed0c3a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
